services:
  hysteria:
    image: tobyxdd/hysteria:latest
    container_name: hysteria
    volumes:
      - ./hysteria/config.yaml:/etc/hysteria/config.yaml
    command: ["server", "-c", "/etc/hysteria/config.yaml"]
    ports:
      - "8443:443/udp"
      - "8443:443/tcp"
    restart: always
    cap_add:
      - NET_ADMIN

  api:
    build: .
    container_name: hysteria-api
    ports:
      - "8000:8000"
    volumes:
      - ./hysteria/config.yaml:/app/hysteria/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_CONFIG__HYSTERIA__CONTAINER_NAME=hysteria
      - APP_CONFIG__RUN__HOST=0.0.0.0
    depends_on:
      - hysteria

